export interface EmojiEntry {
  char: string;
  keywords: string[];
}

export interface EmojiCategory {
  id: string;
  labelKey: string;
  emojis: EmojiEntry[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "people",
    labelKey: "categoryPeople",
    emojis: [
      { char: "😀", keywords: ["grin", "smile", "happy"] },
      { char: "😁", keywords: ["grin", "smile"] },
      { char: "😂", keywords: ["laugh", "joy", "tears"] },
      { char: "🤣", keywords: ["rofl", "laugh"] },
      { char: "😊", keywords: ["smile", "blush"] },
      { char: "😍", keywords: ["love", "heart eyes"] },
      { char: "😘", keywords: ["kiss", "love"] },
      { char: "😜", keywords: ["wink", "tongue"] },
      { char: "🤔", keywords: ["think", "hmm"] },
      { char: "😎", keywords: ["cool", "sunglasses"] },
      { char: "😴", keywords: ["sleep", "tired"] },
      { char: "😭", keywords: ["cry", "sad"] },
      { char: "😡", keywords: ["angry", "mad"] },
      { char: "🥳", keywords: ["party", "celebrate"] },
      { char: "🤗", keywords: ["hug"] },
      { char: "🙌", keywords: ["hands", "celebrate"] },
      { char: "👍", keywords: ["thumbs up", "like", "ok"] },
      { char: "👎", keywords: ["thumbs down"] },
      { char: "👏", keywords: ["clap"] },
      { char: "🙏", keywords: ["pray", "thanks"] },
      { char: "💪", keywords: ["muscle", "strong"] },
      { char: "🧠", keywords: ["brain", "mind"] },
      { char: "👀", keywords: ["eyes", "look"] },
      { char: "🧳", keywords: ["luggage", "travel", "bag"] },
    ],
  },
  {
    id: "nature",
    labelKey: "categoryNature",
    emojis: [
      { char: "🐶", keywords: ["dog"] },
      { char: "🐱", keywords: ["cat"] },
      { char: "🐼", keywords: ["panda"] },
      { char: "🦊", keywords: ["fox"] },
      { char: "🐸", keywords: ["frog"] },
      { char: "🐢", keywords: ["turtle"] },
      { char: "🦋", keywords: ["butterfly"] },
      { char: "🐝", keywords: ["bee"] },
      { char: "🌸", keywords: ["flower", "blossom"] },
      { char: "🌵", keywords: ["cactus"] },
      { char: "🌴", keywords: ["palm", "tree"] },
      { char: "🌈", keywords: ["rainbow"] },
      { char: "🔥", keywords: ["fire", "hot"] },
      { char: "🌙", keywords: ["moon", "night"] },
      { char: "⭐", keywords: ["star"] },
      { char: "❄️", keywords: ["snow", "cold"] },
    ],
  },
  {
    id: "food",
    labelKey: "categoryFood",
    emojis: [
      { char: "🍎", keywords: ["apple"] },
      { char: "🍌", keywords: ["banana"] },
      { char: "🍕", keywords: ["pizza"] },
      { char: "🍔", keywords: ["burger"] },
      { char: "🍟", keywords: ["fries"] },
      { char: "🍣", keywords: ["sushi"] },
      { char: "🍜", keywords: ["noodles", "ramen"] },
      { char: "🍰", keywords: ["cake"] },
      { char: "🍩", keywords: ["donut"] },
      { char: "☕", keywords: ["coffee"] },
      { char: "🍵", keywords: ["tea"] },
      { char: "🥕", keywords: ["carrot"] },
      { char: "🍇", keywords: ["grapes"] },
      { char: "🍫", keywords: ["chocolate"] },
    ],
  },
  {
    id: "activity",
    labelKey: "categoryActivity",
    emojis: [
      { char: "⚽", keywords: ["soccer", "football"] },
      { char: "🏀", keywords: ["basketball"] },
      { char: "🏆", keywords: ["trophy", "win"] },
      { char: "🎮", keywords: ["game", "controller"] },
      { char: "🎯", keywords: ["target", "dart"] },
      { char: "🎨", keywords: ["art", "paint"] },
      { char: "🎵", keywords: ["music", "note"] },
      { char: "🎬", keywords: ["movie", "clapper"] },
      { char: "♟️", keywords: ["chess"] },
      { char: "🎲", keywords: ["dice", "game"] },
    ],
  },
  {
    id: "travel",
    labelKey: "categoryTravel",
    emojis: [
      { char: "✈️", keywords: ["plane", "flight"] },
      { char: "🚗", keywords: ["car"] },
      { char: "🚀", keywords: ["rocket", "launch"] },
      { char: "🚲", keywords: ["bike", "bicycle"] },
      { char: "🗺️", keywords: ["map"] },
      { char: "🏔️", keywords: ["mountain"] },
      { char: "🏖️", keywords: ["beach"] },
      { char: "🗼", keywords: ["tower"] },
      { char: "🏠", keywords: ["home", "house"] },
      { char: "🏢", keywords: ["office", "building"] },
    ],
  },
  {
    id: "objects",
    labelKey: "categoryObjects",
    emojis: [
      { char: "💡", keywords: ["idea", "bulb", "light"] },
      { char: "📄", keywords: ["document", "page", "file"] },
      { char: "📁", keywords: ["folder"] },
      { char: "📌", keywords: ["pin"] },
      { char: "📎", keywords: ["clip", "attach"] },
      { char: "🔑", keywords: ["key"] },
      { char: "🔒", keywords: ["lock", "private"] },
      { char: "💻", keywords: ["laptop", "computer"] },
      { char: "📱", keywords: ["phone", "mobile"] },
      { char: "🔍", keywords: ["search", "magnify"] },
      { char: "📚", keywords: ["books"] },
      { char: "✏️", keywords: ["pencil", "edit", "write"] },
      { char: "📆", keywords: ["calendar", "date"] },
      { char: "⏰", keywords: ["clock", "alarm", "time"] },
      { char: "🎁", keywords: ["gift", "present"] },
    ],
  },
  {
    id: "symbols",
    labelKey: "categorySymbols",
    emojis: [
      { char: "❤️", keywords: ["heart", "love"] },
      { char: "✅", keywords: ["check", "done"] },
      { char: "❌", keywords: ["cross", "no"] },
      { char: "❓", keywords: ["question"] },
      { char: "❗", keywords: ["exclamation", "important"] },
      { char: "💯", keywords: ["hundred", "perfect"] },
      { char: "🔔", keywords: ["bell", "notification"] },
      { char: "🚩", keywords: ["flag"] },
      { char: "♻️", keywords: ["recycle"] },
      { char: "⚡", keywords: ["zap", "lightning", "fast"] },
      { char: "1️⃣", keywords: ["number", "digit", "one", "1"] },
      { char: "2️⃣", keywords: ["number", "digit", "two", "2"] },
      { char: "3️⃣", keywords: ["number", "digit", "three", "3"] },
      { char: "4️⃣", keywords: ["number", "digit", "four", "4"] },
      { char: "5️⃣", keywords: ["number", "digit", "five", "5"] },
      { char: "6️⃣", keywords: ["number", "digit", "six", "6"] },
      { char: "7️⃣", keywords: ["number", "digit", "seven", "7"] },
      { char: "0️⃣", keywords: ["number", "digit", "zero", "0"] },
      { char: "8️⃣", keywords: ["number", "digit", "eight", "8"] },
      { char: "9️⃣", keywords: ["number", "digit", "nine", "9"] },
    ],
  },
  {
    id: "flags",
    labelKey: "categoryFlags",
    emojis: [
      { char: "🇻🇳", keywords: ["vietnam"] },
      { char: "🇺🇸", keywords: ["usa", "united states"] },
      { char: "🇯🇵", keywords: ["japan"] },
      { char: "🇰🇷", keywords: ["korea"] },
      { char: "🇨🇳", keywords: ["china"] },
      { char: "🇬🇧", keywords: ["uk", "britain"] },
      { char: "🇫🇷", keywords: ["france"] },
      { char: "🇩🇪", keywords: ["germany"] },
    ],
  },
];
