import {
  Bell,
  Book,
  Briefcase,
  Calendar,
  Camera,
  Clock,
  Cloud,
  Code,
  Coffee,
  Compass,
  Database,
  FileText,
  Flag,
  Folder,
  Gift,
  Globe,
  Heart,
  Home,
  Image,
  Key,
  Layers,
  Lightbulb,
  Map,
  Music,
  Package,
  Palette,
  Rocket,
  Settings,
  Shield,
  Star,
  Sun,
  Target,
  Trophy,
  Zap,
  type LucideIcon,
} from "lucide-react";

export interface IconOption {
  name: string;
  Icon: LucideIcon;
}

export const ICON_OPTIONS: IconOption[] = [
  { name: "file-text", Icon: FileText },
  { name: "folder", Icon: Folder },
  { name: "star", Icon: Star },
  { name: "heart", Icon: Heart },
  { name: "bell", Icon: Bell },
  { name: "book", Icon: Book },
  { name: "briefcase", Icon: Briefcase },
  { name: "calendar", Icon: Calendar },
  { name: "camera", Icon: Camera },
  { name: "clock", Icon: Clock },
  { name: "cloud", Icon: Cloud },
  { name: "code", Icon: Code },
  { name: "coffee", Icon: Coffee },
  { name: "compass", Icon: Compass },
  { name: "database", Icon: Database },
  { name: "flag", Icon: Flag },
  { name: "gift", Icon: Gift },
  { name: "globe", Icon: Globe },
  { name: "home", Icon: Home },
  { name: "image", Icon: Image },
  { name: "key", Icon: Key },
  { name: "layers", Icon: Layers },
  { name: "lightbulb", Icon: Lightbulb },
  { name: "map", Icon: Map },
  { name: "music", Icon: Music },
  { name: "package", Icon: Package },
  { name: "palette", Icon: Palette },
  { name: "rocket", Icon: Rocket },
  { name: "settings", Icon: Settings },
  { name: "shield", Icon: Shield },
  { name: "sun", Icon: Sun },
  { name: "target", Icon: Target },
  { name: "trophy", Icon: Trophy },
  { name: "zap", Icon: Zap },
];

export const ICON_OPTIONS_BY_NAME: Record<string, LucideIcon> = Object.fromEntries(
  ICON_OPTIONS.map((option) => [option.name, option.Icon]),
);
